CREATE TABLE IF NOT EXISTS medicamento (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    disponivel BOOLEAN NOT NULL
);

INSERT INTO medicamento (nome, categoria, preco, disponivel) VALUES
('Paracetamol', 'Analgesico', 50.00, TRUE),
('Ibuprofeno', 'Anti-inflamatorio', 80.00, TRUE),
('Amoxicilina', 'Antibiotico', 150.00, TRUE),
('Omeprazol', 'Antiacido', 120.00, TRUE),
('Cetirizina', 'Antihistaminico', 70.00, TRUE),
('Loratadina', 'Antihistaminico', 85.00, TRUE),
('Atorvastatina', 'Redutor de colesterol', 250.00, TRUE),
('Simvastatina', 'Redutor de colesterol', 230.00, TRUE),
('Metformina', 'Antidiabetico', 200.00, TRUE),
('Glibenclamida', 'Antidiabetico', 180.00, TRUE),
('Diclofenaco', 'Anti-inflamatorio', 90.00, TRUE),
('Ciprofloxacina', 'Antibiotico', 180.00, TRUE),
('Doxiciclina', 'Antibiotico', 160.00, TRUE),
('Azitromicina', 'Antibiotico', 200.00, TRUE),
('Salbutamol', 'Broncodilatador', 120.00, TRUE),
('Beclometasona', 'Inalador', 250.00, TRUE),
('Fluconazol', 'Antifungico', 140.00, TRUE),
('Clotrimazol', 'Antifungico', 100.00, TRUE),
('Nistatina', 'Antifungico', 90.00, TRUE),
('Loperamida', 'Antidiarreico', 50.00, TRUE),
('Ranitidina', 'Antiacido', 110.00, TRUE),
('Hidroxicloroquina', 'Antimalarico', 300.00, TRUE),
('Artemeter', 'Antimalarico', 350.00, TRUE),
('Praziquantel', 'Antiparasitario', 200.00, TRUE),
('Albendazol', 'Antiparasitario', 90.00, TRUE),
('Fenitoina', 'Antiepileptico', 180.00, TRUE),
('Diazepam', 'Sedativo', 70.00, TRUE),
('Levotiroxina', 'Tireoide', 210.00, TRUE),
('Prednisolona', 'Corticosteroide', 140.00, TRUE),
('Cloroquina', 'Antimalarico', 220.00, TRUE);